"""empty message

Revision ID: 10f56e839063
Revises: 652c9670286b
Create Date: 2025-09-18 00:44:18.295859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f56e839063'
down_revision = '652c9670286b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_planner', sa.Integer(), nullable=False))
        batch_op.drop_constraint('event_organizer_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['event_planner'], ['id'])
        batch_op.drop_column('organizer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('event_organizer_fkey', 'user', ['organizer'], ['id'])
        batch_op.drop_column('event_planner')

    # ### end Alembic commands ###
